### PR TITLE
Fix download issue #27

### LINKED ISSUE #27: Failed to download files with specific characters in their names
Failed to download files with specific characters in their names.

Sample log (dir for local file path is removed for privacy concern):
```
Fail to download these 8 file(s):
Tc xxx - Group Writing & Proposals F21.pptx
Tc xxx - A1, Video Demonstration F21.pptx
...
```

### PR DESCRIPTION
**Pull request by wallace1052**
I found the line where the bug appears and uses another solution to download the files with special characters that cannot be downloaded with the original library.
Fixes #27

### CODE REVIEW

**Review by BoYanZh — COMMENTED** [review]
Could you please the version of `aiohttp` as well as an example url which can be downloaded with `requests` but not `aiothtp`?

**Comment by wallace1052** [comment]
The version is 3.8.0.
One example link is listed below from #27 
> Fail to download these 8 file(s):
https://umich.instructure.com/files/21062535/download?download_frd=1&verifier=j8ypj92qvk3e028W3svq1uX82FuqO38Os63w13wE => Kumpf, TechComTip_Layout_Choices.pdf

**Comment by BoYanZh** [comment]
Could you please try #29? You can install it according to 'Install From Source', with an extra `git checkout develop` right after clone.

**Comment by wallace1052** [comment]
Ok, I will try now, thanks for your update

**Comment by wallace1052** [comment]
The current version works quite well now, and can also deal with the files with special characters

**Pull request closed without merging**
