### PR TITLE
detect big file and ask before download

### PR DESCRIPTION
**Pull request by XYPB**
bmm jw用request写QAQ

### CODE REVIEW

**Comment by XYPB** [comment]
好 我会了

**Comment by Scarlet1ssimo** [comment]
tqlb

**Review by BoYanZh — CHANGES_REQUESTED** [review]
???

**Comment by XYPB** [comment]
jbdxbl

**Comment by Scarlet1ssimo** [comment]
nice traget

**Comment by XYPB** [comment]
bksw

**Pull request merged**
